baseURL = 'https://milesvant.github.io'
languageCode = 'en-us'
title = "Miles VT's Blog"
theme = "hugo-theme-codex"
googleAnalytics = "G-YLT7R3DZYL"

[params]
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  github = "https://github.com/milesvant"
  email = "mailto:milesvant@gmail.com"
  linkedin = "https://www.linkedin.com/in/miles-van-tongeren-55270b119/"

  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported:
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub", "Email", "LinkedIn"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts"
